use_frameworks!

target 'XSSegmentedView_Example' do
  pod 'XSSegmentedView', :path => '../'

  target 'XSSegmentedView_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
